# Generated by Django 3.2.6 on 2021-08-03 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название здания')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': '  Здания',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название узла')),
                ('host', models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IP-адрес')),
                ('image', models.ImageField(blank=True, null=True, upload_to='nodes_photo', verbose_name='Фото')),
                ('is_monitoring', models.BooleanField(default=False, verbose_name='Мониторинг')),
                ('key', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Ключ сессии')),
                ('time_delta', models.FloatField(blank=True, null=True, verbose_name='Разница времени')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dispatcher.building', verbose_name='Здание')),
            ],
            options={
                'verbose_name': 'Узел',
                'verbose_name_plural': '  Узлы',
                'ordering': ['building', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название оборудования')),
                ('host', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP-адрес')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dispatcher.node', verbose_name='Узел')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудования',
                'ordering': ['node', 'name', 'host'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dispatcher.unit')),
            ],
            options={
                'get_latest_by': 'time',
            },
        ),
    ]
