# Generated by Django 3.2.6 on 2021-08-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='is_monitoring',
        ),
        migrations.RemoveField(
            model_name='node',
            name='key',
        ),
        migrations.RemoveField(
            model_name='node',
            name='time_delta',
        ),
    ]
