# Generated by Django 3.2.6 on 2021-08-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dispatcher', '0002_auto_20210804_1132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('unit', 'time')},
        ),
    ]
