# Generated by Django 3.2.6 on 2021-08-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dispatcher', '0003_alter_measurement_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
