# Generated by Django 3.2.6 on 2021-09-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dispatcher', '0004_alter_measurement_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='port',
            field=models.IntegerField(blank=True, default=48620, null=True, verbose_name='Порт'),
        ),
    ]
