# Generated by Django 3.2.6 on 2021-09-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dispatcher', '0005_unit_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='port',
            field=models.IntegerField(blank=True, default=48620, null=True, verbose_name='Порт'),
        ),
    ]
